# Generated by Django 5.2.9 on 2025-12-23 15:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="APIKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("key", models.CharField(max_length=128, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("allowed_ips", models.JSONField(blank=True, null=True)),
            ],
            options={
                "db_table": "etl_apikey",
            },
        ),
        migrations.CreateModel(
            name="ETLBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("partner_id", models.IntegerField()),
                ("partner_batch_id", models.CharField(max_length=100)),
                ("total_samples", models.IntegerField()),
                ("raw_payload", models.JSONField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "etl_batch",
                "indexes": [
                    models.Index(
                        fields=["partner_id", "partner_batch_id"],
                        name="etl_batch_partner_377e76_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ETLStageSampleIntake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("partner_id", models.IntegerField()),
                ("partner_batch_id", models.CharField(max_length=100)),
                (
                    "partner_record_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("sample_code", models.CharField(max_length=60)),
                ("sampling_date", models.DateField(blank=True, null=True)),
                ("year", models.IntegerField()),
                ("stage", models.IntegerField(default=1)),
                ("lab_number", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "company_external_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "laboratory_external_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "trial_external_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("extra", models.JSONField(blank=True, null=True)),
                ("raw_payload", models.JSONField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api_etl.etlbatch",
                    ),
                ),
            ],
            options={
                "db_table": "etl_stage_sampleintake",
            },
        ),
        migrations.CreateModel(
            name="ETLStageSampleIntakeValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("indicator_code", models.CharField(max_length=100)),
                (
                    "method_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("unit_code", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "value_numeric",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=12, null=True
                    ),
                ),
                ("value_text", models.CharField(blank=True, max_length=200, null=True)),
                ("extra", models.JSONField(blank=True, null=True)),
                (
                    "stage_sampleintake",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api_etl.etlstagesampleintake",
                    ),
                ),
            ],
            options={
                "db_table": "etl_stage_sampleintake_value",
            },
        ),
        migrations.AddIndex(
            model_name="etlstagesampleintake",
            index=models.Index(
                fields=["partner_id", "partner_batch_id"],
                name="etl_stage_s_partner_4ec50e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="etlstagesampleintake",
            index=models.Index(
                fields=["sample_code", "year", "lab_number"],
                name="etl_stage_s_sample__664983_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="etlstagesampleintakevalue",
            index=models.Index(
                fields=["indicator_code"], name="etl_stage_s_indicat_2f32b6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="etlstagesampleintakevalue",
            index=models.Index(
                fields=["method_code"], name="etl_stage_s_method__430e81_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="etlstagesampleintakevalue",
            index=models.Index(
                fields=["unit_code"], name="etl_stage_s_unit_co_f3e8b7_idx"
            ),
        ),
    ]
